# -*- coding: utf-8 -*-
"""spacelab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/AlikePro/fd16ddc741c794402f9fd8c40cb8c443/spacelab.ipynb
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import pearsonr
csv_df = pd.read_excel("Алма_данные_обработано.xlsx", sheet_name="Интерполированные данные")
quakes_df = pd.read_excel("Almaty_seismic_events_2015_2020.xlsx", sheet_name="Almaty")
quakes_df["Date"] = pd.to_datetime(dict(year=quakes_df["yr"], month=quakes_df["Mon"], day=quakes_df["Day"]))
csv_df["Data"] = pd.to_datetime(csv_df["Data"], dayfirst=True, errors='coerce')
quakes_daily = quakes_df.groupby("Date").agg({
    "M": ["count", "mean", "max"]
}).reset_index()
quakes_daily.columns = ["Date", "QuakeCount", "MeanMagnitude", "MaxMagnitude"]
merged_df = pd.merge(quakes_daily, csv_df, left_on="Date", right_on="Data", how="left")
merged_df.drop(columns=["Data"], inplace=True)
merged_df.dropna(inplace=True)
features = merged_df.drop(columns=["Date", "QuakeCount", "MeanMagnitude", "MaxMagnitude"])
targets = merged_df[["QuakeCount", "MeanMagnitude", "MaxMagnitude"]]
results = {}
for target_name in targets.columns:
    corr_vals = []
    p_vals = []
    for feature_name in features.columns:
        corr, p = pearsonr(features[feature_name], targets[target_name])
        corr_vals.append(corr)
        p_vals.append(p)
    results[target_name] = pd.DataFrame({
        "Feature": features.columns,
        "Correlation": corr_vals,
        "PValue": p_vals
    })
for target_name, df in results.items():
    df_sig = df[df["PValue"] <= 0.05].sort_values(by="Correlation", ascending=False)
    plt.figure(figsize=(14, 6))
    sns.barplot(data=df_sig, x="Feature", y="Correlation")
    plt.xticks(rotation=90)
    plt.title(f"Значимая корреляция признаков с {target_name}")
    plt.ylabel("Коэффициент корреляции (p value ≤ 0.05)")
    plt.xlabel("Признаки")
    plt.grid(True)
    plt.tight_layout()
    plt.show()